polls/urls.py
from django.urls import path

from polls import views

app_name = 'polls'
urlpatterns=[
    path('',views.index, name='index'), #views안의 index파일과 연결
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote', views.vote, name='vote'),
]

pollsite/urls.py
from django.contrib import admin
from django.urls import path

from polls.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', index),
]

polls/models.py
from django.db import models


# Create your models here. 모델만들기
class Question(models.Model):
    question_text = models.CharField(max_length=200)  # 데이터 타입 문자열
    pub_date = models.DateTimeField('date published')  # 데이터 타입 날짜


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)  # 칼럼은 외래키로 Question과 연결됨
    choice_text = models.CharField(max_length=200)  # 문자열
    votes = models.IntegerField(default=0)  # 정수

# 테이블 두개 만드는 것 부모테이블 자식테이블

polls/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse

from polls.models import Question, Choice


# 함수 형 view , 클래스형 view
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    output = ', '.join([q.question_text for q in latest_question_list])
    return HttpResponse(output)

polls/templates/detail.html
<h1> {{ question.question_text}}</h1>
{% if error_message  %}<p> <strong> {{error_message}} </strong></p> {% endif %}

<form action ="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
        <label for="choice{{ forloop.counter }}"> {{ choice.choice_text }}</label> <br/>
    {% endfor %}
    <input type="submit" value="Vote"/>
</form>

polls/templates/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>가능한 여론(polls)가 없어요</p>
{% endif %}

polls/templates/result.html
<h1>{{ question.question_text}}</h1>
<ul>
    {% for choice in question.choice_set.all %}
        <li> {{ choice.choice_text }} -- {{ choice.votes }} vote {{ choice.votes | pluralize }} </li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">다시 투표하실래요?</a>